"""add fts for english

Revision ID: a8e6bca12c86
Revises: 212754afd1b3
Create Date: 2023-04-03 16:40:36.597510

"""
from alembic import op
import sqlalchemy as sa
import sys
sys.path.append(".")
import api

# revision identifiers, used by Alembic.
revision = 'a8e6bca12c86'
down_revision = '212754afd1b3'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ts_vector', api.db.ts.TSVector(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True))
    op.create_index('ix_video_ts_vector', 'documents', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_ts_vector', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'ts_vector')
    # ### end Alembic commands ###
